services:
  envoy:
    image: envoyproxy/envoy:v1.27.0
    container_name: rest_envoy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./RestLoadBalancer/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./Certifications:/etc/ssl/certs/:ro
    command:
      [
        "envoy",
        "-c",
        "/etc/envoy/envoy.yaml",
        "--log-level",
        "debug",
        "--component-log-level",
        "config:trace,upstream:trace",
      ]
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - 2181
    restart: always
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
    restart: always
  redis:
    image: redis:7-alpine
    container_name: redis
    expose:
      - 6379
    command: redis-server --appendonly yes
    restart: always
  market-server:
    build:
      context: MarketExecution
    image: market-server:latest
    container_name: market-server
    environment:
      KAFKA_BROKERS: "kafka:9092"
    depends_on:
      - kafka
    restart: always
  rest-server:
    build:
      context: RestAPI
    container_name: RestAPI
    expose:
      - 8080
    restart: always
  postgres_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: maxime
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
  jwt-check:
    build:
      context: JwtCheck
    container_name: jwt-check
    expose:
      - 50051
    restart: always
volumes:
  postgres_data:
